In [1]:
import numpy as np

In [2]:
def check(sudoku,i,j,k):
    for x in range(9):
        if (sudoku[x][j] == k) or (sudoku[i][x] == k):
            return False
        
    x = (i//3)*3
    y = (j//3)*3
    for q in range(x,x+3):
        for w in range(y,y+3):
            if sudoku[q][w] == k:
                return False
    return True

In [3]:
def solve(sudoku):
    global n
    for i in range(9):
        for j in range(9):
            if sudoku[i][j] == 0:
                for k in range(1,10):
                    if check(sudoku,i,j,k):
                        sudoku[i][j]=k
                        solve(sudoku)
                        sudoku[i][j]=0
                return
    print("answer",n)
    print(np.matrix(sudoku),"\n")
    n=n+1

In [4]:
# EXAMPLE
sudoku = [  [0,0,7,9,3,0,0,0,8],
            [6,8,0,0,0,5,0,9,0],
            [0,0,0,0,0,0,0,0,2],
            [0,0,0,4,0,0,0,8,0],
            [5,0,0,1,0,6,0,3,0],
            [0,6,0,0,0,0,0,0,0],
            [0,0,1,0,5,4,0,0,0],
            [0,0,9,7,0,0,0,0,1],
            [0,0,0,0,0,0,0,7,0]   ]

In [5]:
n=1
solve(sudoku)

answer 1
[[4 2 7 9 3 1 5 6 8]
 [6 8 3 2 4 5 1 9 7]
 [9 1 5 6 7 8 3 4 2]
 [1 3 2 4 9 7 6 8 5]
 [5 9 8 1 2 6 7 3 4]
 [7 6 4 5 8 3 2 1 9]
 [8 7 1 3 5 4 9 2 6]
 [3 4 9 7 6 2 8 5 1]
 [2 5 6 8 1 9 4 7 3]] 



In [6]:
# empty sudoku for edit
sudoku_empty = [[0,0,0,0,0,0,0,0,0],
                [0,0,0,0,0,0,0,0,0],
                [0,0,0,0,0,0,0,0,0],
                [0,0,0,0,0,0,0,0,0],
                [0,0,0,0,0,0,0,0,0],
                [0,0,0,0,0,0,0,0,0],
                [0,0,0,0,0,0,0,0,0],
                [0,0,0,0,0,0,0,0,0],
                [0,0,0,0,0,0,0,0,0]]